### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by kibitan** [kibitan/masking#10]
- load configuration
   - [ ] `masking.yml` generator
   - [ ] validate `masking.yml` ( format / exists )
 - write integration test
   - [ ] with types
   - [ ] make unit test decoupled
 - refactoring
   - [ ] rename Masking::Config::TargetColumns::Column::Method
   - [ ] extract Masking::Config::TargetColumns::TargetColumns.tables ( yaml parser )
   - [ ] singletonize Masking::Config::TargetColumns
   - [ ] rename Masking::Config::TargetColumns
   - [ ] refactoring inside of DataMaskProcessor.process
   - [ ] rename DataMaskProcessor
 - [ ] publish to gem
 - [ ] publish to HomeBrew?
